import {chainFrame,splitPattern} from './playback.js';
let chain=null,chainLoop=0,shownLoop=-1;
import {bindDial} from './knob.js';
const dialSync=[];
import {MusicBrain,SCALES,rng,clamp,midiPitch,parseMidi,midiExamples,exportMidi} from './core.js';
import {retainedOutput} from './midi-output.js';
import {AcidSynth} from './audio.js';
import {validatePattern,validateSession,DEFAULT_TONE} from './session.js';
let tone={...DEFAULT_TONE};
const $=id=>document.getElementById(id), KEY='fruitfly-acid-session-v1';
let graph,brain,steps=[],settings={bpm:128,root:0,scale:'Minor',length:16,density:68,mutation:42,accent:75,slide:33},seed=303,slots=Array(4).fill(null),selected=-1,frozen=false,history=[],playing=false,current=-1,scheduled=[],nextTime=0,nextStep=0,timer=null,epoch=0,midiAccess=null,midiOutput=null,motion=matchMedia('(prefers-reduced-motion: reduce)').matches,activity=[],learned=0;
const synth=new AcidSynth();
const say=(s,error=false)=>{$('status').textContent=s;$('status').classList.toggle('error',error);};
const names=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
for(let i=0;i<12;i++)$('root').add(new Option(names[i],i));
for(const key of ['density','mutation','accent','slide']){const el=document.createElement('div');el.className='knob';el.innerHTML=`<label for="${key}">${key.toUpperCase()}</label><div class="dial" id="dial-${key}"></div><output id="value-${key}" for="${key}"></output><input id="${key}" type="range" min="0" max="100" value="${settings[key]}" aria-label="${key}">`;$('knobs').append(el);dialSync.push(bindDial($('dial-'+key),$(key),key));$(key).oninput=()=>{settings[key]=Number($(key).value);updateKnobs();};$(key).onchange=()=>{make(false);say(`${key} updated · new unlocked variation`);};}
function updateKnobs(){for(const key of ['density','mutation','accent','slide']){$(key).value=settings[key];$('value-'+key).textContent=settings[key];$('dial-'+key).style.setProperty('--arc',settings[key]*2.7+'deg');$('dial-'+key).style.setProperty('--angle',settings[key]*2.7-135+'deg');}}
function snapshot(){return {settings:structuredClone(settings),steps:structuredClone(steps),seed};}
function remember(){history.push(snapshot());if(history.length>30)history.shift();$('undo').disabled=false;}

function data(){return {version:1,graphVersion:graph.version,pattern:snapshot(),slots,brain:brain.export(),tone,frozen,learned};}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(data()));}catch{say('Browser storage unavailable · use Save session for a backup',true);}}
function load(d){const valid=validateSession(d,graph),p=valid.pattern;stop();brain=new MusicBrain(graph,valid.brain);settings=p.settings;steps=p.steps;seed=p.seed;slots=valid.slots;tone=valid.tone;frozen=valid.frozen;learned=valid.learned;history=[];selected=-1;sync();}
function sync(){for(const k of ['cutoff','resonance','volume','decay','delayTime','feedback','wet','kickLevel'])$(k).value=tone[k];updateTone();for(const k of ['bpm','root','scale','length'])$(k).value=settings[k];updateKnobs();render();renderSlots();freezeUI();dialSync.forEach(sync=>sync());}
function render(pattern={steps,settings}){const {steps,settings}=pattern;const g=$('grid');g.style.setProperty('--steps',settings.length);g.replaceChildren();const rows=['step','note','accent','slide','locked'];for(const row of rows){const label=document.createElement('div');label.className='cell label';label.textContent={step:'STEP',note:'NOTE',accent:'ACCENT',slide:'SLIDE',locked:'LOCK'}[row];g.append(label);steps.forEach((s,i)=>{const b=document.createElement('button');b.disabled=playing&&!!chain;b.dataset.index=i;b.className='cell '+row;if(row==='step'){b.textContent=String(i+1).padStart(2,'0');b.onclick=()=>edit(i,'gate');b.setAttribute('aria-label',`Step ${i+1}, ${s.gate?'on':'rest'}, toggle`);}else if(row==='note'){b.classList.toggle('rest',!s.gate);b.style.setProperty('--note',s.degree);const bar=document.createElement('span'),em=document.createElement('em');em.textContent=s.gate?names[midiPitch(s,settings)%12]:'—';b.append(bar,em);b.setAttribute('aria-label',`Step ${i+1} note ${em.textContent}. Click to change, Shift-click to rest.`);b.onclick=e=>edit(i,e.shiftKey?'gate':'degree');}else if(row==='locked'){b.textContent=s.locked?'◆':'◇';b.classList.toggle('locked',s.locked);b.setAttribute('aria-label',`Lock step ${i+1}`);b.setAttribute('aria-pressed',s.locked);b.onclick=()=>edit(i,'locked');}else{b.classList.add(s[row]?'active':'off');b.setAttribute('aria-label',`${row} step ${i+1}`);b.setAttribute('aria-pressed',s[row]);b.onclick=()=>edit(i,row);}g.append(b);});}paintStep(current);$('undo').disabled=!history.length;$('lock').textContent=steps.every(s=>s.locked)?'UNLOCK ALL':'LOCK ALL';activity=steps[Math.max(0,current)]?.activity||[];}
function edit(i,k){remember();if(k==='degree'){steps[i].degree=(steps[i].degree+1)%7;steps[i].gate=true;}else steps[i][k]=!steps[i][k];render();persist();}
function make(newSeed=true){if(!brain)return;remember();if(newSeed)seed=crypto.getRandomValues(new Uint32Array(1))[0];steps=brain.generate(settings,seed,steps);render();persist();}
function renderSlots(){$('slots').replaceChildren();slots.forEach((s,i)=>{const b=document.createElement('button');b.textContent='A'+(i+1);b.className=(s?'filled ':'')+(selected===i?'selected':'');b.setAttribute('aria-label',s?`Recall saved pattern A${i+1}`:`Save current pattern to A${i+1}`);b.onclick=()=>{if(s){remember();const p=validatePattern(s,graph);settings=p.settings;steps=p.steps;seed=p.seed;selected=i;sync();persist();say(`Recalled A${i+1}`);}else{slots[i]=snapshot();selected=i;renderSlots();persist();say(`Saved A${i+1} · existing slots are preserved`);}};$('slots').append(b);});}
function freezeUI(){$('freeze').setAttribute('aria-pressed',frozen);$('freeze').querySelector('span').textContent=frozen?'LEARNING FROZEN':'FREEZE LEARNING';$('feed').disabled=frozen;$('learn').disabled=frozen;}
function train(examples,label){if(frozen){say('Learning is frozen');return;}const result=brain.train(examples);learned++;persist();say(`${label} · fit loss ${result.before.toFixed(2)} → ${result.after.toFixed(2)} · generate to hear learned variations`);}
function download(bytes,name,type){const url=URL.createObjectURL(new Blob([bytes],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function stamp(){return new Date().toISOString().replace(/[:.]/g,'-');}
function paintStep(i){document.querySelectorAll('.cell[data-index]').forEach(el=>el.classList.toggle('playing',playing&&Number(el.dataset.index)===i));}
function sendMidi(s,i,time,duration,pattern={steps,settings}){const {steps,settings}=pattern;if(!midiOutput)return;const ms=performance.now()+(time-synth.context.currentTime)*1000;try{if(s.gate){const pitch=midiPitch(s,settings);midiOutput.send([0x90,pitch,s.accent?115:78],ms);midiOutput.send([0x80,pitch,0],ms+duration*(s.slide?1.05:.8)*1000);}}catch(e){say('MIDI output disconnected: '+e.message,true);midiOutput=null;}}
function schedule(){if(!playing)return;const c=synth.context;if(nextTime<c.currentTime-.1){nextTime=c.currentTime+.03;scheduled=[];synth.stop();}while(nextTime<c.currentTime+.1){if(chain&&nextStep===0)chain=splitPattern(snapshot());const frame=chain?chainFrame(chain,chainLoop,nextStep):null,pattern=frame?.pattern||{steps,settings},i=nextStep%pattern.steps.length,s=pattern.steps[i],duration=60/settings.bpm/4;if(tone.kickOn&&i%4===0)synth.kick.hit(nextTime,tone.kickLevel);const nextPattern=frame?chainFrame(chain,frame.next.loop,frame.next.step).pattern:pattern;const following=nextPattern.steps[frame?frame.next.step:(i+1)%pattern.steps.length];const slide=s.slide&&following.gate;if(s.gate)synth.note(midiPitch(s,pattern.settings),nextTime,duration,s.accent,slide,tone.cutoff,tone.resonance,tone.volume,tone.decay,midiPitch(following,nextPattern.settings));else synth.rest(nextTime);sendMidi({...s,slide},i,nextTime,duration,pattern);scheduled.push({i,time:nextTime,activity:s.activity,pattern,loop:chainLoop,slot:frame?.slot});nextTime+=duration;if(frame){chainLoop=frame.next.loop;nextStep=frame.next.step;}else nextStep=(i+1)%steps.length;}}

async function play(){if(playing){stop();return;}chain=$('play-mode').value==='aaab'?splitPattern(snapshot()):null;chainLoop=0;shownLoop=-1;const token=++epoch;try{await synth.start();synth.fx.set(tone.delayTime,tone.feedback,tone.wet);if(token!==epoch)return;playing=true;nextStep=0;if(chain)render(chain[0]);nextTime=synth.context.currentTime+.05;scheduled=[];$('play').textContent='Ⅱ';$('play').setAttribute('aria-label','Pause');schedule();timer=setInterval(schedule,25);say('Playing · Space to stop');}catch(e){say('Audio could not start: '+e.message,true);}}
function stop(){epoch++;playing=false;clearInterval(timer);timer=null;scheduled=[];current=-1;synth.stop();if(midiOutput)try{midiOutput.clear();midiOutput.send([0xb0,123,0]);midiOutput.send([0xb0,120,0]);}catch{}$('play').textContent='▶';$('play').setAttribute('aria-label','Play');paintStep(-1);chain=null;shownLoop=-1;if(steps.length)render();$('chain-position').textContent='';}
$('kick-toggle').onclick=()=>{tone.kickOn=tone.kickOn?0:1;if(!tone.kickOn)synth.kick?.stop();updateTone();persist();};$('play-mode').onchange=()=>{stop();say($('play-mode').value==='aaab'?'AAAB · first half × 3 → second half · current pattern':'Single pattern playback');};$('play').onclick=play;$('stop').onclick=()=>{stop();say('Stopped');};$('generate').onclick=()=>{make();say('New variation · seed '+seed);};$('undo').onclick=()=>{const p=history.pop();if(!p)return;settings=p.settings;steps=p.steps;seed=p.seed;sync();persist();say('Previous pattern restored');};$('clear').onclick=()=>{remember();steps=steps.map(s=>s.locked?s:{...s,gate:false});render();persist();say('Unlocked steps cleared');};$('lock').onclick=()=>{remember();const lock=!steps.every(s=>s.locked);steps.forEach(s=>s.locked=lock);render();persist();};
for(const k of ['bpm','root','scale','length'])$(k).onchange=()=>{remember();const val=$(k).value;settings[k]=k==='scale'?val:k==='bpm'?clamp(Number(val)||128,40,240):Number(val);$(k).value=settings[k];if(k==='length'){steps=brain.generate(settings,seed,steps);nextStep%=steps.length;}render();persist();};
$('keep').onclick=()=>{const index=slots.indexOf(null);if(index<0){download(JSON.stringify({version:1,graphVersion:graph.version,pattern:snapshot(),slots,brain:brain.export(),tone,frozen,learned},null,2),'fruitfly-keep-'+stamp()+'.json','application/json');say('All slots full · saved a new session file without overwriting patterns');return;}slots[index]=snapshot();selected=index;renderSlots();persist();say('Kept in A'+(index+1));};
$('freeze').onclick=()=>{frozen=!frozen;freezeUI();persist();say(frozen?'Learning frozen · patterns can still be edited and generated':'Learning enabled');};$('learn').onclick=()=>train(steps,'Current pattern reinforced');$('feed').onclick=()=>$('midi-file').click();
$('midi-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(frozen)throw Error('Unfreeze learning before importing MIDI');const parsed=parseMidi(await file.arrayBuffer()),examples=midiExamples(parsed,settings,graph);train(examples,`${file.name} · ${examples.length} quantized steps`);}catch(e){say(e.message,true);}finally{e.target.value='';}};
$('export').onclick=()=>{download(exportMidi(steps,settings),'fruitfly-acid-'+stamp()+'.mid','audio/midi');say('Exported MIDI · overlapping notes encode slides');};$('save-session').onclick=()=>download(JSON.stringify(data(),null,2),'fruitfly-session-'+stamp()+'.json','application/json');$('load-session').onclick=()=>$('session-file').click();$('session-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>8*1024*1024)throw Error('Session exceeds 8 MB');load(JSON.parse(await file.text()));persist();say('Session restored');}catch(e){say('Cannot load session: '+e.message,true);}finally{e.target.value='';}};
$('about').onclick=()=>$('credits').showModal();$('credits').querySelector('.close').onclick=()=>$('credits').close();$('reset-learning').onclick=()=>{if(!confirm('Reset only the learned musical weights? Your saved patterns will remain.'))return;brain=new MusicBrain(graph);learned=0;persist();say('Learned weights reset · saved patterns preserved');};
$('motion').onclick=()=>{motion=!motion;$('motion').textContent=motion?'RESUME MOTION':'PAUSE MOTION';$('motion').setAttribute('aria-pressed',motion);};$('motion').textContent=motion?'RESUME MOTION':'PAUSE MOTION';$('motion').setAttribute('aria-pressed',motion);
for(const key of ['cutoff','resonance','decay','volume','delayTime','feedback','wet','kickLevel']){const dial=document.createElement('div');dial.className='dial';dial.id='dial-'+key;$(key).before(dial);dialSync.push(bindDial(dial,$(key),({volume:'Level',delayTime:'Delay time',feedback:'Feedback',wet:'Wet/Dry',kickLevel:'Kick level'})[key]||key));}
function updateTone(){$('kickLevel-value').textContent=Math.round(tone.kickLevel*100)+'%';$('kick-toggle').setAttribute('aria-pressed',tone.kickOn===1);$('kick-toggle').textContent=tone.kickOn?'KICK ON':'KICK OFF';$('delayTime-value').textContent=Math.round(tone.delayTime*1000)+' ms';$('feedback-value').textContent=Math.round(tone.feedback*100)+'%';$('wet-value').textContent=Math.round(tone.wet*100)+'% WET';dialSync.forEach(sync=>sync());$('decay-value').textContent=Math.round(tone.decay*1000)+' ms';$('cutoff-value').textContent=tone.cutoff+' Hz';$('resonance-value').textContent=tone.resonance.toFixed(1);$('volume-value').textContent=Math.round(tone.volume/.65*100)+'%';}
for(const k of ['cutoff','resonance','volume','decay','delayTime','feedback','wet','kickLevel'])$(k).oninput=()=>{tone[k]=Number($(k).value);updateTone();if(playing)synth.fx?.set(tone.delayTime,tone.feedback,tone.wet);if(k==='volume'&&synth.context)synth.master.gain.setTargetAtTime(tone.volume,synth.context.currentTime,.02);persist();};

function midiPorts(){const previous=midiOutput,retained=retainedOutput(midiAccess.outputs,previous);if(previous&&!retained){stop();say('MIDI output disconnected · playback stopped',true);}midiOutput=retained;const s=$('midi-port');s.replaceChildren(new Option('MIDI OFF',''));for(const o of midiAccess.outputs.values())if(o.state==='connected')s.add(new Option(o.name,o.id));s.value=midiOutput?.id||'';s.hidden=false;}
$('midi').onclick=async()=>{try{if(!navigator.requestMIDIAccess)throw Error('This browser does not support live MIDI. Export MIDI, or open in Brave/Chrome.');midiAccess=await navigator.requestMIDIAccess({sysex:false});midiPorts();midiAccess.onstatechange=midiPorts;say(midiAccess.outputs.size?'Select an output port':'No MIDI output ports found · connect a device or enable a virtual port');}catch(e){say(e.message,true);}};$('midi-port').onchange=()=>{stop();midiOutput=midiAccess.outputs.get($('midi-port').value)||null;say(midiOutput?'MIDI connected: '+midiOutput.name:'MIDI output off');};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){stop();return;}if($('credits').open||['INPUT','SELECT','BUTTON','TEXTAREA'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();play();}if(e.key.toLowerCase()==='g')$('generate').click();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){stop();say('Paused while hidden · press Play to resume');}});window.addEventListener('pagehide',stop);
const canvas=$('brain'),ctx=canvas.getContext('2d');let frame=0,lastDraw=0;function draw(time){requestAnimationFrame(draw);if(document.hidden||time-lastDraw<33)return;lastDraw=time;while(scheduled.length&&scheduled[0].time<=(synth.context?.currentTime||0)){const s=scheduled.shift();current=s.i;activity=s.activity;if(chain&&shownLoop!==s.loop){shownLoop=s.loop;render(s.pattern);$('chain-position').textContent=`${s.slot===0?'A · FIRST HALF':'B · SECOND HALF'} / ${s.loop%4+1} OF 4`;}paintStep(current);}const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(rect.width*dpr)||canvas.height!==Math.round(rect.height*dpr)){canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,h=rect.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#24465122';ctx.lineWidth=.5;for(let x=0;x<w;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}const cx=w/2,cy=h*.43,k=Math.min(w/720,h/380);if(!graph)return;const xs=graph.nodes.map(n=>n.position[0]),ys=graph.nodes.map(n=>n.position[1]),minx=Math.min(...xs),miny=Math.min(...ys),dx=Math.max(...xs)-minx,dy=Math.max(...ys)-miny;const coords=graph.nodes.map(n=>[cx+((n.position[0]-minx)/dx-.5)*250*k,cy+((n.position[1]-miny)/dy-.5)*195*k]);let energy=0;for(const [a,b,weight] of graph.edges){const v=Math.abs(activity[a]||0);if(weight<12)continue;ctx.strokeStyle=`rgba(66,203,204,${.025+v*.12})`;ctx.lineWidth=.4+Math.min(weight/250,1)*.5;ctx.beginPath();ctx.moveTo(...coords[a]);ctx.lineTo(...coords[b]);ctx.stroke();}for(let i=0;i<coords.length;i++){const v=Math.abs(activity[i]||0);energy+=v;const [x,y]=coords[i];ctx.fillStyle=`rgba(100,245,210,${.25+v*.7})`;ctx.shadowColor='#52ffd2';ctx.shadowBlur=v*14;ctx.beginPath();ctx.arc(x,y,1+v*3,0,Math.PI*2);ctx.fill();}ctx.shadowBlur=0;canvas.parentElement.style.setProperty('--fly-brightness',!motion&&playing?String(.85+energy/graph.nodes.length*.55):'1');if(!motion&&playing){frame+=.012;for(let n=0;n<8;n++){const e=graph.edges[(n*137)%graph.edges.length],v=Math.abs(activity[e[0]]||0);if(v<.08)continue;const t=(frame+n/8)%1,a=coords[e[0]],b=coords[e[1]];ctx.fillStyle='#b7ffed';ctx.beginPath();ctx.arc(a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,1.6,0,Math.PI*2);ctx.fill();}}}
async function init(){try{const response=await fetch('data/connectome.json');if(!response.ok)throw Error('Circuit data unavailable');graph=await response.json();brain=new MusicBrain(graph);steps=brain.generate(settings,seed);$('circuit-label').innerHTML=graph.nodes.length+' NEURONS<br>'+graph.edges.length.toLocaleString()+' CONNECTIONS';let loaded=false,loadError=false;try{const saved=localStorage.getItem(KEY);if(saved){load(JSON.parse(saved));loaded=true;}}catch(e){loadError=true;say('Saved state could not be restored · original data kept in browser storage',true);}sync();if(!loadError)say(loaded?'Session restored · press Play':'Ready · press Play to hear your first pattern');requestAnimationFrame(draw);}catch(e){say(e.message,true);document.querySelectorAll('button').forEach(b=>b.disabled=true);}}
init();
