import {Kick} from './kick.js';
import {DelayFX} from './delay.js';
export class AcidSynth{
 constructor(){this.context=null;this.voices=[];}
 async start(){if(!this.context){const c=this.context=new AudioContext();this.osc=c.createOscillator();this.osc.type='sawtooth';this.filter=c.createBiquadFilter();this.filter.type='lowpass';this.filter2=c.createBiquadFilter();this.filter2.type='lowpass';this.filter2.frequency.value=8000;this.amp=c.createGain();this.amp.gain.value=0;const shaper=c.createWaveShaper(),curve=new Float32Array(2048);for(let i=0;i<curve.length;i++){let x=i/(curve.length-1)*2-1;curve[i]=Math.tanh(2*x)/Math.tanh(2);}shaper.curve=curve;shaper.oversample='2x';this.master=c.createGain();this.master.gain.value=.22;this.limiter=c.createDynamicsCompressor();this.limiter.threshold.value=-12;this.limiter.knee.value=12;this.limiter.ratio.value=8;this.osc.connect(this.filter).connect(this.filter2).connect(this.amp).connect(shaper);this.fxSource=shaper;this.master.connect(this.limiter).connect(c.destination);this.kick=new Kick(c,this.limiter);this.osc.start();}if(this.fx)this.fx.dispose();this.fx=new DelayFX(this.context,this.fxSource,this.master);await this.context.resume();}
 note(pitch,time,duration,accent,slide,cutoff,resonance,volume,decay=.24,nextPitch=pitch){const f=440*2**((pitch-69)/12),o=this.osc.frequency,g=this.amp.gain,ff=this.filter.frequency;g.cancelAndHoldAtTime(time);this.master.gain.setTargetAtTime(volume,time,.02);this.filter.Q.setTargetAtTime(resonance,time,.01);if(this.sliding){o.setValueAtTime(f,time);}else{o.setValueAtTime(f,time);g.linearRampToValueAtTime(accent?.75:.5,time+.01);}if(!this.sliding){ff.cancelAndHoldAtTime(time);ff.linearRampToValueAtTime(Math.min(15000,cutoff*(accent?3.5:2)),time+.01);ff.exponentialRampToValueAtTime(Math.max(65,cutoff*.35),time+decay*.85);}if(slide){const target=440*2**((nextPitch-69)/12),end=time+duration;o.setValueAtTime(f,end-Math.min(.065,duration*.5));o.exponentialRampToValueAtTime(target,end);}if(!slide)g.exponentialRampToValueAtTime(.001,time+decay);this.sliding=slide;}
 rest(time){if(this.sliding){this.amp.gain.cancelAndHoldAtTime(time);this.amp.gain.exponentialRampToValueAtTime(.001,time+.02);}this.sliding=false;}
 stop(){if(!this.context)return;let t=this.context.currentTime;for(const p of [this.osc.frequency,this.amp.gain,this.filter.frequency,this.filter.Q,this.master.gain])p.cancelScheduledValues(t);this.amp.gain.setTargetAtTime(0,t,.01);this.fx?.stop();this.kick?.stop();this.sliding=false;}
}
