import test from 'node:test';import assert from 'node:assert/strict';import {AcidSynth} from '../audio.js';
function parameter(){return {events:[],linearRampToValueAtTime(...v){this.events.push(['linear',...v]);},setTargetAtTime(...v){this.events.push(['target',...v]);},setValueAtTime(...v){this.events.push(['set',...v]);},exponentialRampToValueAtTime(...v){this.events.push(['ramp',...v]);},cancelAndHoldAtTime(...v){this.events.push(['hold',...v]);},cancelScheduledValues(...v){this.events.push(['cancel',...v]);}};}
function synth(){const s=new AcidSynth();s.osc={frequency:parameter()};s.amp={gain:parameter()};s.filter={frequency:parameter(),Q:parameter()};s.master={gain:parameter()};s.context={currentTime:1.2};return s;}
test('long decay rings across rests; next note replaces the old envelope',()=>{const s=synth();s.note(48,1,.12,false,false,1100,7,.22,.4);assert.ok(s.amp.gain.events.some(e=>e[0]==='ramp'&&e[1]===.001&&e[2]===1.4));const before=s.amp.gain.events.length;s.rest(1.12);assert.equal(s.amp.gain.events.length,before);s.note(50,1.24,.12,false,false,1100,7,.22,.4);assert.ok(s.amp.gain.events.some(e=>e[0]==='hold'&&e[1]===1.24));});
test('stop cancels a long tail and releases output',()=>{const s=synth();s.note(48,1,.12,true,false,1100,7,.22,1.5);s.stop();assert.deepEqual(s.amp.gain.events.slice(-2),[['cancel',1.2],['target',0,1.2,.01]]);});
test('slide lands on the next pitch exactly at the step boundary without filter retrigger',()=>{const s=synth();s.note(48,1,.12,false,true,1100,7,.22,.4,60);const target=440*2**((60-69)/12);assert.ok(s.osc.frequency.events.some(e=>e[0]==='ramp'&&e[1]===target&&e[2]===1.12));const filterCount=s.filter.frequency.events.length,pitchCount=s.osc.frequency.events.length;s.note(60,1.12,.12,false,false,1100,7,.22,.4);assert.equal(s.filter.frequency.events.length,filterCount);assert.deepEqual(s.osc.frequency.events.slice(pitchCount),[['set',target,1.12]]);});
test('a rest after a sustained slide releases the voice',()=>{const s=synth();s.note(48,1,.12,false,true,1100,7,.22,.4);s.rest(1.12);assert.ok(s.amp.gain.events.some(e=>e[0]==='ramp'&&e[1]===.001&&Math.abs(e[2]-1.14)<1e-9));assert.equal(s.sliding,false);});

test('retrigger uses a short continuous attack instead of an abrupt gain reset',()=>{const s=synth();s.note(48,1,.12,false,false,1100,7,.22,.4);s.note(50,1.12,.12,false,false,1100,7,.22,.4);assert.equal(s.amp.gain.events.filter(e=>e[0]==='set').length,0);assert.ok(s.amp.gain.events.some(e=>e[0]==='linear'&&e[1]===.5&&Math.abs(e[2]-1.13)<1e-9));});
