export const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export const SCALES={Minor:[0,2,3,5,7,8,10],Dorian:[0,2,3,5,7,9,10],Phrygian:[0,1,3,5,7,8,10],Major:[0,2,4,5,7,9,11]};
export function rng(seed){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
const sigmoid=x=>1/(1+Math.exp(-clamp(x,-30,30)));
function softmax(a,temp=1){const m=Math.max(...a),v=a.map(x=>Math.exp((x-m)/temp)),s=v.reduce((a,b)=>a+b,0);return v.map(x=>x/s);}
function sample(p,r){let x=r();for(let i=0;i<p.length;i++){x-=p[i];if(x<=0)return i;}return p.length-1;}
export class Circuit{
 constructor(graph){this.graph=graph;this.state=new Float64Array(graph.nodes.length);let sums=new Float64Array(this.state.length);for(const [a,b,w] of graph.edges)sums[b]+=w;this.edges=graph.edges.map(([a,b,w])=>[a,b,w/(sums[b]||1)*graph.nodes[a].sign]);}
 step(phase,previous,seed){const r=rng(seed),stim=[Math.sin(phase*2*Math.PI),Math.cos(phase*2*Math.PI),phase<.25?1:-.3,previous/7,Math.sin(phase*8*Math.PI),1, r()*2-1,r()*2-1];
 for(let t=0;t<5;t++){const next=new Float64Array(this.state.length);for(const [a,b,w] of this.edges)next[b]+=this.state[a]*w*1.8;for(const [a,c] of this.graph.inputs)next[a]+=stim[c]*1.1;for(let i=0;i<next.length;i++)this.state[i]=.55*this.state[i]+.45*Math.tanh(next[i]);}
 return [1,...this.graph.outputs.map(i=>this.state[i]),Math.sin(phase*2*Math.PI),Math.cos(phase*2*Math.PI),Math.sin(phase*8*Math.PI),previous/7];}
}
export class MusicBrain{
 constructor(graph,weights){this.graph=graph;this.size=graph.outputs.length+5;this.weights=Array.from({length:10},()=>Array(this.size).fill(0));this.updates=0;if(weights)this.load(weights);else{const r=rng(303);this.weights=this.weights.map(row=>row.map(()=> (r()-.5)*.6));this.weights[0][0]=.8;this.weights[4][0]=.35;}}
 load(d){if(!Array.isArray(d.weights)||d.weights.length!==10||d.weights.some(r=>!Array.isArray(r)||r.length!==this.size||r.some(x=>!Number.isFinite(x)||Math.abs(x)>100)))throw Error('Invalid learned weights');this.weights=d.weights.map(r=>r.slice());this.updates=Number.isSafeInteger(d.updates)?Math.max(0,d.updates):0;}
 export(){return {weights:this.weights.map(r=>r.slice()),updates:this.updates};}
 logits(f){return this.weights.map(row=>row.reduce((s,w,i)=>s+w*f[i],0));}
 generate(settings,seed,old=[]){const c=new Circuit(this.graph),r=rng(seed);let prev=0;const steps=[];for(let i=0;i<settings.length;i++){const f=c.step((i%16)/16,prev,(seed+i)>>>0),l=this.logits(f),degree=sample(softmax(l.slice(0,7),.35+settings.mutation/70),r);const note={degree,gate:r()<clamp(sigmoid(l[7])+(settings.density-50)/100,.02,.98),accent:r()<clamp(sigmoid(l[8])*.3+settings.accent/120-.15,0,1),slide:r()<clamp(sigmoid(l[9])*.2+settings.slide/125-.1,0,.95),locked:false,features:f,activity:Array.from(c.state)};steps.push(old[i]?.locked?structuredClone(old[i]):note);prev=steps[i].degree;}return steps;}
 train(examples,epochs=12,rate=.035){let before=this.loss(examples);for(let e=0;e<epochs;e++)for(const s of examples){if(!s.features||s.features.length!==this.size)continue;const l=this.logits(s.features),p=softmax(l.slice(0,7));for(let k=0;k<10;k++){const err=k<7?(s.gate?((k===s.degree?1:0)-p[k]):0):Number(s[['gate','accent','slide'][k-7]])-sigmoid(l[k]);for(let j=0;j<this.size;j++)this.weights[k][j]=clamp(this.weights[k][j]+rate*err*s.features[j],-12,12);}}this.updates+=examples.length*epochs;return {before,after:this.loss(examples)};}
 loss(examples){if(!examples.length)return 0;return examples.reduce((sum,s)=>{const l=this.logits(s.features),p=softmax(l.slice(0,7));let v=s.gate?-Math.log(Math.max(1e-8,p[s.degree])):0;for(let k=7;k<10;k++){const q=sigmoid(l[k]),yes=s[['gate','accent','slide'][k-7]];v-=Math.log(Math.max(1e-8,yes?q:1-q));}return sum+v;},0)/examples.length;}
}
export function midiPitch(step,settings){return 36+Number(settings.root)+SCALES[settings.scale][step.degree];}
function vlq(n){let out=[n&127];while(n>>=7)out.unshift((n&127)|128);return out;}
export function exportMidi(steps,settings){const events=[];const tempo=Math.round(60000000/settings.bpm);events.push([0,[255,81,3,tempo>>16&255,tempo>>8&255,tempo&255]]);for(let i=0;i<steps.length;i++){const s=steps[i];if(!s.gate)continue;const start=i*120,pitch=midiPitch(s,settings),tie=s.slide&&steps[(i+1)%steps.length]?.gate;events.push([start,[144,pitch,s.accent?115:78]]);events.push([start+(tie?126:90),[128,pitch,0]]);}events.sort((a,b)=>a[0]-b[0]||a[1][0]-b[1][0]);let data=[],last=0;for(const [t,msg]of events){data.push(...vlq(t-last),...msg);last=t;}data.push(...vlq(Math.max(0,steps.length*120-last)),255,47,0);let n=data.length;return new Uint8Array([77,84,104,100,0,0,0,6,0,0,0,1,1,224,77,84,114,107,n>>>24&255,n>>>16&255,n>>>8&255,n&255,...data]);}
export function parseMidi(buffer){const b=new Uint8Array(buffer);if(b.length>4*1024*1024)throw Error('MIDI file exceeds 4 MB');const v=new DataView(b.buffer,b.byteOffset,b.byteLength);let p=0;const need=n=>{if(p+n>b.length)throw Error('Truncated MIDI file');};const u16=()=>{need(2);let x=v.getUint16(p);p+=2;return x;};const u32=()=>{need(4);let x=v.getUint32(p);p+=4;return x;};const str=()=>{need(4);let s=String.fromCharCode(...b.slice(p,p+4));p+=4;return s;};if(str()!=='MThd')throw Error('Choose a standard MIDI file');const header=u32();if(header<6)throw Error('Invalid MIDI header');const format=u16(),tracks=u16(),ppq=u16();if(format>1||!ppq||(ppq&32768))throw Error('Use format 0/1 MIDI with beat-based timing');p=8+header;let notes=[],bpm=128;for(let t=0;t<tracks;t++){if(str()!=='MTrk')throw Error('Invalid MIDI track');const len=u32(),end=p+len;if(end>b.length)throw Error('Truncated MIDI track');let tick=0,status=0,active=new Map();const read=()=>{if(p>=end)throw Error('Truncated MIDI event');return b[p++];};const varlen=()=>{let x=0;for(let i=0;i<4;i++){let c=read();x=(x<<7)|(c&127);if(!(c&128))return x;}throw Error('Invalid MIDI timing');};while(p<end){tick+=varlen();let s=read();if(s<128){if(status<128||status>=240)throw Error('Invalid running status');p--;s=status;}else if(s<240)status=s;else status=0;if(s===255){let type=read(),n=varlen();if(p+n>end)throw Error('Invalid MIDI metadata');if(type===81&&n===3)bpm=60000000/((b[p]<<16)|(b[p+1]<<8)|b[p+2]);p+=n;if(type===47){p=end;break;}continue;}if(s===240||s===247){const count=varlen();p+=count;if(p>end)throw Error('Invalid MIDI sysex');continue;}if(s>=240)throw Error('Unsupported MIDI status');const kind=s>>4,ch=s&15,a=read(),d=(kind===12||kind===13)?0:read();if(a>127||d>127)throw Error('Invalid MIDI data');if(ch===9)continue;const key=ch*128+a;if(kind===9&&d>0){if(active.has(key)){let old=active.get(key);notes.push({...old,end:tick});}active.set(key,{start:tick,pitch:a,velocity:d});}else if(kind===8||(kind===9&&d===0)){let n=active.get(key);if(n){notes.push({...n,end:Math.max(tick,n.start+1)});active.delete(key);}}}for(const n of active.values())notes.push({...n,end:Math.max(tick,n.start+ppq/4)});}
 if(notes.length>50000)throw Error('MIDI contains too many notes; import a shorter clip');if(!notes.length)throw Error('No pitched notes found (drums are ignored)');notes.sort((a,b)=>a.start-b.start||a.pitch-b.pitch);return {notes,ppq,bpm:clamp(Math.round(bpm)||128,40,240)};}
export function midiExamples(parsed,settings,graph){const first=parsed.notes[0].start,unit=parsed.ppq/4,end=parsed.notes.reduce((m,n)=>Math.max(m,n.end),0),length=Math.min(2048,Math.max(16,Math.ceil((end-first)/unit)));const c=new Circuit(graph);let prev=0;const examples=[];for(let i=0;i<length;i++){const tick=first+i*unit;const candidates=parsed.notes.filter(n=>Math.round((n.start-first)/unit)===i).sort((a,b)=>a.pitch-b.pitch);const n=candidates[0];let degree=0;if(n){let best=999;for(let d=0;d<7;d++){const pc=((n.pitch-Number(settings.root))%12+12)%12,delta=Math.abs(pc-SCALES[settings.scale][d]),dist=Math.min(delta,12-delta);if(dist<best){degree=d;best=dist;}}}const features=c.step((i%16)/16,prev,303+i);examples.push({degree,gate:!!n,accent:!!n&&n.velocity>=100,slide:!!n&&n.end>tick+unit,locked:false,features,activity:Array.from(c.state)});prev=degree;}return examples;}
